basePath: /backend/v1
definitions:
  serializer.Response:
    properties:
      code:
        description: 自定义状态码
        type: integer
      data:
        type: object
      error:
        type: object
      msg:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: 1269879928@qq.com
    name: shjting
    url: 106.53.5.146
  license: {}
  title: 后端相关
  version: "1.0"
paths:
  /administrator/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: email
        in: path
        name: email
        required: true
        type: string
      - description: password
        in: path
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 后台登录接口
      tags:
      - 登录
swagger: "2.0"
